fe/.eslintrc.js, fe/.storybook/main.js, fe/.storybook/webpack.config.js, fe/package-lock.json, fe/package.json, fe/src/components/atoms/PriceTag/PriceTag.stories.tsx, fe/src/components/atoms/PriceTag/index.tsx, fe/src/components/atoms/PriceTag/style.ts, fe/src/styles/theme.ts, fe/yarn.lock
가격을 표기 하기 위한 컴포넌트를 생성 하였습니다. 
`bold 적용`
@kimwonyong
@kwangdosa
=> PriceTag 컴포넌트 생성

be/src/apis/urls/index.ts, be/src/controllers/auth/index.ts, be/src/routers/api/auth/index.ts, be/src/services/auth/index.ts, fe/package.json, fe/src/App.tsx, fe/src/apis/auth.ts, fe/src/apis/axios.ts, fe/src/apis/user.ts, fe/src/components/molecules/GithubButton/index.tsx, fe/src/pages/OauthCallbackPage/index.tsx, fe/yarn.lock
- axios instance사용
- github oauth callback을 BE를 거치지 않고 바로 FE로 가도록 수정
=> Fix : Oauth 로그인 수정

be/src/services/transaction/index.ts, fe/src/components/organisms/Calender/index.tsx, fe/src/components/organisms/Calender/style.ts, fe/src/components/organisms/CalenderBind/index.stories.tsx, fe/src/components/organisms/CalenderBind/index.tsx, fe/src/components/organisms/CalenderBind/style.ts, fe/src/pages/CalenderPage/index.tsx, fe/src/pages/MainPage/index.tsx, fe/src/pages/StatisticsPage/index.tsx, fe/src/stores/Transaction/index.ts, fe/src/utils/date.ts
```ts
getOneMonthRange: (year: string, month: string) => {
if (month === '12') {
return {
startDate: new Date(`${year}-${month}`),
endDate: new Date(`${Number(year) + 1}-${1}`),
};
}
return {
startDate: new Date(`${year}-${month}`),
endDate: new Date(`${year}-${Number(month) + 1}`),
};
},
```
date 타입으로 리턴하게 했고 사용하는 곳들 수정했습니다.
[이번 PR 변경사항](https://github.com/boostcamp-2020/Project16-A-Account-Book/pull/133/files/67d38923090bfb1850702a3a3cdd1976196a0e4a..8cff073c5064a85cae0b64db5b4884b76d8ce73d)
closes #132 
=> getOneMonthRange 함수 date타입 리턴하도록 수정

be/src/controllers/account/index.ts, be/src/models/account/index.ts, be/src/models/account/static.ts, be/src/models/user/index.ts, be/src/routers/api/account/index.ts, be/src/seeds/index.ts, be/src/seeds/user.ts, be/src/services/account/index.ts, be/src/services/auth/index.ts, fe/src/App.tsx, fe/src/apis/account.ts, fe/src/apis/urls/index.ts, fe/src/components/organisms/NavBar/index.tsx, fe/src/hooks/useAccountInfo.ts, fe/src/pages/AccountListPage/index.tsx, fe/src/pages/AuthCheck/index.tsx, fe/src/pages/OauthCallbackPage/index.tsx, fe/src/stores/Account/index.ts, fe/src/stores/Transaction/index.ts
기존 경로 : `/transaction/:title`
변경 경로 : `/transaction/:owner/:title`
- 경로 변경에 따른 Store, API, 기타 로직 수정
- owner와 title로 accountObjId 가져오는 API 생성
accountObjId를 세션 스토리지에서 제거를 했는데, accountObjId를 가져온 뒤에 넣어두고 쓰면 api 호출을 줄일 수 있을 것 같습니다. 
closes #128 
=> 프로젝트 라우팅 수정 

fe/src/components/molecules/InvitationItem/style.ts, fe/src/components/organisms/InvitationList/index.stories.tsx, fe/src/components/organisms/InvitationList/index.tsx, fe/src/components/organisms/InvitationList/style.ts, fe/src/components/organisms/MainFilterForm/index.tsx
=> 알림 목록 리스트 컴포넌트 생성 

fe/src/components/molecules/Transaction/style.ts, fe/src/styles/theme.ts
=> 메인페이지 Transaction 스타일 수정

fe/src/components/atoms/DatePicker/style.ts, fe/src/components/molecules/DateRange/index.tsx, fe/src/components/molecules/DateRange/style.ts
=> Date Picker Input 길이 수정

be/src/controllers/category/index.ts, be/src/libs/error.ts, be/src/middlewares/index.ts, be/src/models/account/index.ts, be/src/models/account/static.ts, be/src/routers/api/category/index.ts, be/src/routers/api/method/index.ts, be/src/services/category/index.ts, fe/src/components/atoms/DatePicker/index.tsx, fe/src/components/atoms/DatePicker/style.ts, fe/src/components/molecules/CategoryDropdown/style.ts, fe/src/components/molecules/DateRange/index.tsx, fe/src/components/molecules/DateRange/style.ts, fe/src/components/molecules/DropdownBody/style.ts, fe/src/components/molecules/DropdownHeader/index.tsx, fe/src/components/organisms/HeaderBar/index.tsx, fe/src/components/organisms/HeaderBar/style.ts, fe/src/components/organisms/MainFilterForm/style.ts, fe/src/components/organisms/TransactionInputField/index.tsx, fe/src/components/organisms/TransactionInputField/style.ts, fe/src/components/templates/FormTransaction/style.ts, fe/src/components/templates/MainTemplate/style.ts, fe/src/pages/CategoryPage/index.tsx, fe/src/pages/CreateTransactionPage/index.tsx, fe/src/pages/UpdateTransactionPage/index.tsx
HeaderBar 컴포넌트에 back  prop을 추가하여 선택적으로 뒤로가기 버튼이 보이도록 하였습니다.
=> 생성/수정 페이지에 뒤로가기 버튼 생성

fe/src/apis/user.ts
=> 머지할 때 중괄호 없어졌던 것 수정

fe/package.json, fe/src/apis/user.ts
=> 오류 수정 후 배포 

fe/src/apis/user.ts, fe/src/components/atoms/ToggleSwitch/style.ts, fe/src/components/molecules/DateRange/style.ts, fe/src/components/molecules/TabHeader/style.ts, fe/src/components/organisms/AccountSubmitButtonList/style.ts, fe/src/components/organisms/MonthInfoHeader/index.tsx, fe/src/components/organisms/MonthInfoHeader/style.ts, fe/src/components/organisms/NoData/index.tsx, fe/src/components/organisms/NoData/style.ts, fe/src/pages/404Page/index.tsx, fe/src/pages/AccountListPage/index.tsx, fe/src/pages/AuthCheck/index.tsx, fe/src/pages/NotFoundPage/index.tsx, fe/src/pages/NotFoundPage/style.ts
=> 메인, 달력페이지 데이터 없을 때 화면 수정 / 카테고리 TabUI css수정

fe/package.json, fe/src/components/atoms/CircleSvg/index.tsx, fe/src/components/atoms/CircleSvg/style.ts, fe/src/components/atoms/DatePicker/index.tsx, fe/src/components/atoms/PriceTag/index.tsx, fe/src/components/molecules/LineChart/index.tsx, fe/src/components/molecules/LineChart/style.ts, fe/src/components/organisms/MonthInfoHeader/index.tsx, fe/src/components/organisms/TransactionList/index.tsx, fe/src/components/templates/CategoryTemplate/index.tsx, fe/src/components/templates/CategoryTemplate/style.ts, fe/src/components/templates/FormTransaction/index.tsx, fe/src/components/templates/FormTransaction/style.ts, fe/src/components/templates/MainTemplate/index.tsx, fe/src/components/templates/MainTemplate/style.ts, fe/src/pages/CategoryPage/index.tsx, fe/src/stores/Transaction/index.ts, fe/src/styles/GlobalStyle.ts, fe/src/utils/date.ts
storke-dasharray를 조작하여 애니메이션 생성하였습니다. 
기존에는 바로 값이 할당되었지만, 애니메이션의 `to` 값으로 넘겨줬습니다.
=> 차트 애니메이션 생성

fe/src/pages/CategoryPage/index.tsx
=> 카테고리 페이지 변경

be/src/middlewares/index.ts
=> [BE] Fix: next빠진 것 수정

fe/src/pages/NotFoundPage/index.tsx, fe/src/pages/NotFoundPage/style.ts
404페이지에 뒤로가기 버튼을 추가했습니다.
closes #292 
=> [FE] Refactor : 404페이지 뒤로가기 버튼 추가

fe/src/components/organisms/TransactionInputField/style.ts
=> [FE] Style : 드랍다운에 폰트 적용

fe/src/components/atoms/DatePicker/style.ts
최소 길이를 4rem으로 지정하여 최소한 안가려지게 수정 하였습니다.
=> [FE] style : datepicker 날짜 가져지는 버그 수정

fe/src/components/molecules/CalendarOneDate/index.tsx, fe/src/components/molecules/CalendarOneDate/style.ts, fe/src/components/molecules/DropdownHeader/style.ts, fe/src/components/molecules/GithubButton/index.tsx, fe/src/components/molecules/GithubButton/style.ts, fe/src/components/organisms/AccountImageTitleUpdate/style.ts, fe/src/components/organisms/Calendar/style.ts, fe/src/components/organisms/CalendarBind/index.tsx, fe/src/components/organisms/ChattingArea/style.ts, fe/src/components/organisms/FilterBar/index.tsx, fe/src/components/organisms/FilterBar/style.ts, fe/src/components/organisms/MonthInfoHeader/index.tsx, fe/src/components/templates/LoginTemplate/index.tsx, fe/src/components/templates/LoginTemplate/style.ts, fe/src/pages/AccountUpdatePage/index.tsx, fe/src/pages/CategoryPage/index.tsx, fe/src/pages/LoginPage/index.tsx, fe/src/pages/LoginPage/style.ts, fe/src/stores/Chatting/index.ts, fe/src/styles/GlobalStyle.ts
로그인 페이지를 만들었습니다.
반응형으로 하려고 했는데 width & height 둘다 고려하려니 잘 안되서 우선 크기를 고정했습니다.
closes #338
=> 로그인 페이지 생성

fe/src/components/molecules/CalendarOneDate/index.tsx, fe/src/components/molecules/CalendarOneDate/style.ts, fe/src/components/organisms/Calendar/style.ts, fe/src/components/organisms/CalendarBind/index.tsx, fe/src/styles/GlobalStyle.ts
미분류 항목도 달력에서 모달 띄우도록 했습니다.
closes #321
=> 달력 미분류 항목 모달 안뜨던 것 수정

fe/src/components/molecules/CalendarOneDate/index.tsx, fe/src/components/molecules/CalendarOneDate/style.ts, fe/src/components/molecules/DropdownHeader/style.ts, fe/src/components/organisms/AccountImageTitleUpdate/style.ts, fe/src/components/organisms/Calendar/style.ts, fe/src/components/organisms/CalendarBind/index.tsx, fe/src/components/organisms/FilterBar/index.tsx, fe/src/components/organisms/FilterBar/style.ts, fe/src/styles/GlobalStyle.ts
필터 검색 아이콘 제거했습니다.
아이폰에서 필터 버튼 글씨 깨졌던 것 width조절로 키워 해결했습니다.
closes #317 
=> 필터바에 검색 아이콘 삭제 / 아이폰에서 필터 글씨 깨졌던 것 수정

fe/src/components/molecules/CalendarOneDate/index.tsx, fe/src/components/molecules/CalendarOneDate/style.ts, fe/src/components/molecules/DropdownHeader/style.ts, fe/src/components/organisms/AccountImageTitleUpdate/style.ts, fe/src/components/organisms/Calendar/style.ts, fe/src/components/organisms/CalendarBind/index.tsx, fe/src/components/organisms/FilterBar/index.tsx, fe/src/components/organisms/FilterBar/style.ts, fe/src/pages/AccountUpdatePage/index.tsx, fe/src/pages/CategoryPage/index.tsx, fe/src/styles/GlobalStyle.ts
Owner가 아닐 때 정말 나가시겠습니까 메세지 띄우도록 수정했습니다.
'정말 나가시겠습니까?' 로 수정
closes #323 
=> 가계부 Owner가 아닌 사람이 가계부 나가기할 때 경고 메세지 수정

fe/src/components/molecules/CalendarOneDate/index.tsx, fe/src/components/molecules/CalendarOneDate/style.ts, fe/src/components/molecules/DropdownHeader/style.ts, fe/src/components/organisms/AccountImageTitleUpdate/style.ts, fe/src/components/organisms/Calendar/style.ts, fe/src/components/organisms/CalendarBind/index.tsx, fe/src/components/organisms/ChattingArea/style.ts, fe/src/components/organisms/FilterBar/index.tsx, fe/src/components/organisms/FilterBar/style.ts, fe/src/pages/AccountUpdatePage/index.tsx, fe/src/pages/CategoryPage/index.tsx, fe/src/styles/GlobalStyle.ts
=> 채팅페이지 오른쪽 치우친 것 수정

fe/src/components/molecules/CalendarOneDate/index.tsx, fe/src/components/molecules/CalendarOneDate/style.ts, fe/src/components/molecules/DropdownHeader/style.ts, fe/src/components/organisms/AccountImageTitleUpdate/style.ts, fe/src/components/organisms/Calendar/style.ts, fe/src/components/organisms/CalendarBind/index.tsx, fe/src/components/organisms/ChattingArea/style.ts, fe/src/components/organisms/FilterBar/index.tsx, fe/src/components/organisms/FilterBar/style.ts, fe/src/components/organisms/MonthInfoHeader/index.tsx, fe/src/pages/AccountUpdatePage/index.tsx, fe/src/pages/CategoryPage/index.tsx, fe/src/stores/Chatting/index.ts, fe/src/styles/GlobalStyle.ts
채팅 버튼을 누르면 채팅 내역을 삭제하는 방식으로 구현
-
closes #337 
=> 채팅페이지 초기화 하도록 수정

fe/src/components/organisms/MonthInfoHeader/index.tsx, fe/src/components/organisms/MonthInfoHeader/style.ts, fe/src/pages/CategoryPage/index.tsx
- 기존에는 카테고리의 경고가 alert로 떴었는데, 이를 모달창에 메시지를 주는 형식으로 변경하였습니다.
closes #278 
=> 카테고리의 에러는 alert가 아닌 모달에 나오도록 수정

fe/src/components/molecules/IconText/style.ts, fe/src/components/organisms/MonthInfoHeader/index.tsx
=> 헤더바에 원 추가 & 가계부에 배치 변경

fe/src/components/molecules/IconText/style.ts
=> [FE] Fix: 가계부 수정 친구 목록 화면 scale하면 화면 넘는 것 수정

fe/src/components/molecules/IconText/style.ts
IOS TransactionHeader undefined나오는 문제 수정
=> [FE] Fix: IOS TransactionHeader undefined나오는 문제 수정

fe/src/pages/AccountListPage/index.tsx
=> [FE] Fix : 가계부페이지 세션 값 수정
