boostcamp-2020/Project16-A-Account-Book

.github/PULL_REQUEST_TEMPLATE.md

멘토님 네 분을 전부 멘션해야 하므로 멘토님 네 분의 깃헙 아이디를 모두 멘션한다.

Fix: 멘토님 네 분을 PR에 멘션하는 것으로 수정

---

fe/.eslintrc.js
fe/src/components/molecules/DropdownHeader/DropdownHeader.stories.tsx
fe/src/components/molecules/DropdownHeader/index.tsx
fe/src/components/molecules/DropdownHeader/style.ts

- 해더에 `visible` state를 가지고 있어서 하단 컨텐츠를 보여주고 사라지도록 하였습니다.
- document에 click 이벤트와 Ref를 이용하여 현재 element이외에 클릭 했을 때 컨텐츠가 사라지도록 하였습니다.

DropdownHeader 컴포넌트 생성

---

fe/src/components/atoms/Button/index.tsx
fe/src/components/atoms/PriceTag/PriceTag.stories.tsx
fe/src/styles/GlobalStyle.ts
fe/src/styles/GlobalThemeProvider.tsx

```js
return (
<ThemeProvider theme={theme}>
<GlobalStyle />
{children}
</ThemeProvider>
);
```
- 스토리북에서 계속 theme를 불러와서 적용해야 함 -> 적용한 것을 리턴하는 컴포넌트 생성
- 추가적으로 GlobalStyle도 같이 전역으로 사용되어 같이 묶음.

글로벌 스타일 지정 및 ThemeProvider와 합침

---

be/src/controllers/transaction/index.ts
be/src/services/transaction/index.ts

year, month로 query를 날리던 걸 startDate, endDate로 수정했습니다.
closes #82 

TransactionAPI year, month를 startDate, endDate로 수정

---

be/src/controllers/transaction/index.ts
be/src/models/account/index.ts
be/src/services/transaction/index.ts

Transaction GET API를 쓸 때 AccountId에 맞는 Transaction만 보여주게 수정했습니다.
```api/transactions/:obj_id``` <- 필수
closes #54 

Transaction GET API가 accountid 참고해서 가져오도록 수정

---

be/src/controllers/transaction/index.ts
be/src/models/account/index.ts
be/src/services/transaction/index.ts
fe/src/pages/MainPage/TransactionDateList.tsx
fe/src/stores/Transaction/transactionStoreUtils.ts

Transaction GET Api 호출에 실패하면 프론트에서 발생하는 에러 핸들링 코드 추가
https://github.com/boostcamp-2020/Project16-A-Account-Book/pull/99/files/a7841ca159d364fbc1c22b40fd93e08ae46ce6ca..253b7569df0f6245ebcadbab69472f401166aaa1

프론트에서 transaction get시 데이터 없을 때 에러 핸들링

---

be/src/services/transaction/index.ts
fe/src/pages/CalenderPage/index.tsx
fe/src/pages/MainPage/index.tsx
fe/src/pages/StatisticsPage/index.tsx
fe/src/stores/Transaction/index.ts

수입 지출 : 중간에 수입 지출을 의미
기존 : 필요한 수입 지출을 Page에서 직접 구해줬음
개선 : mobx 의 calculate로 mobx단에서 계산해서 리턴하도록 수정 
Transasction Store가 DB에서 값을 가져오는 PENDING 상태일 때 totalPrices 를 { income: 0, expense: 0 } 을 return하도록 수정했는데 0, 0에서 새로 계산된 값으로 바뀌는 과정에서 깜빡임이 있음 이 것 수정 #114
#113 -> 논의 필요

MonthInfoHeader에 필요한 수입 지출 calculate로 구하도록 수정

---

be/src/services/transaction/index.ts
fe/src/components/organisms/Calender/index.tsx
fe/src/components/organisms/Calender/style.ts
fe/src/components/organisms/CalenderBind/index.stories.tsx
fe/src/components/organisms/CalenderBind/index.tsx
fe/src/components/organisms/CalenderBind/style.ts
fe/src/pages/CalenderPage/index.tsx
fe/src/pages/MainPage/index.tsx
fe/src/pages/StatisticsPage/index.tsx
fe/src/stores/Transaction/index.ts

기존 : 달력 페이지가 한달치 데이터만 보여줬음
변경 : 설정된 기간동안 있는 달력을 보여줌
기존 논의할 때 시작 날짜에서 달력이 시작해서 (ex 10월 12일 부터 달력이 시작)
끝나는 날짜에 달력이 끝나도록 구현하기로 논의했었는데
1. 구현이 복잡하고
2. 사용자도 한 달 통째로 보는게 사용자 경험 상 좋을 것 같아
시작 일자부터 달력을 만드는게 아닌, 시작 일자의 달 첫날 기준으로 달력을 만들게 했습니다 (ex 10월 12일 부터 데이터가 있으면 달력은 10월 1일부터 출발)
10월에 데이터 O
11월에 데이터 X
12월에 데이터 O
라면
11월 달력은 보여주지 않고 10월과 12월만 보여주게 했습니다.
사용자 경험상 어떤게 좋을지 논의해보고 11월 달력을 보여주는게 좋다면 추가로 수정해야 합니다.
메인페이지나 달력페이지에서 데이터가 하나도 없을 때 뭘 보여줄 지 논의해보면 좋을 것 같습니다. 
메인페이지는 데이터가 없습니다. 라는 화면(을 많이 꾸며서)을 보여주면 될 것 같고
달력페이지는 같이 표시하거나 빈 달력하나를 표시하는 방법이 있을 것 같습니다.
https://github.com/boostcamp-2020/Project16-A-Account-Book/pull/118/files/9d717d60b5bd77457a94605dedcd1ec25ff5a221..896bc301cd6091f1aa391b2f960056ed313131dd
메인페이지, 달력페이지 데이터 없을 때 보여줄 화면 생성 #117
closes #116 

달력페이지 기간별 데이터 보여줄 수 있도록 수정

---

be/src/controllers/transaction/index.ts
be/src/services/transaction/index.ts
fe/src/components/organisms/Calender/index.tsx
fe/src/components/organisms/Calender/style.ts
fe/src/components/organisms/CalenderBind/index.stories.tsx
fe/src/components/organisms/CalenderBind/index.tsx
fe/src/components/organisms/CalenderBind/style.ts
fe/src/pages/CalenderPage/index.tsx
fe/src/pages/MainPage/index.tsx
fe/src/pages/StatisticsPage/index.tsx
fe/src/stores/Transaction/index.ts
fe/src/utils/date.ts

기존에 데이터가 없을 때 { message: 'nodata' } 로 BE에서 응답하던걸 
빈 배열 return 후 204 상태코드를 띄우도록 수정했습니다.
[이번 PR 변경사항](https://github.com/boostcamp-2020/Project16-A-Account-Book/pull/134/files/8cff073c5064a85cae0b64db5b4884b76d8ce73d..d7d303f478e49779294596f7c2433c209505d007)
closes #125

Transaction 없을 때 'nodata' 리턴했던 것 빈 배열로 수정

---

be/src/app.ts
be/src/controllers/transaction/index.ts
be/src/libs/error.ts
be/src/models/transaction/index.ts
be/src/models/transaction/static.ts
be/src/routers/api/transaction/index.ts
be/src/seeds/transaction.ts
be/src/services/transaction/index.ts

- transaction schema에 isDeleted 필드를 추가하고, 시드 데이터에도 추가하였습니다.
기본값은 false입니다.
- 하나의 거래내역을 가져오는 API의 url은 다음과 같습니다. 
```
/transactions/:transactionObjId/detail
```
- API를 포스트맨 example에 추가하였습니다.
- 잘못된 object id이거나, 삭제된 거래내역에 접근할 시, 400 에러와 다음과 같은 에러 메시지를 띄웁니다.
```
잘못된 Transaction Id이거나, 삭제된 Transaction에 접근하였습니다.
```
- 에러의 status와 message를 libs/error.ts에 추가하였습니다.
```ts
export const invalidTransactionError = {
status: 400,
message: '잘못된 Transaction Id이거나, 삭제된 Transaction에 접근하였습니다.',
};
```
저희가 에러 핸들링에 대한 response 표준화가 안되어 있는 것 같습니다. 
에러일 때의 response 표준화를 정하는 것이 좋지 않을까 생각이 듭니다!
closes #140 

하나의 거래내역 가져오는 API 추가

---

fe/src/components/organisms/Calender/index.stories.tsx
fe/src/components/organisms/Calender/index.tsx
fe/src/components/organisms/CalenderBind/index.stories.tsx
fe/src/components/organisms/CalenderBind/index.tsx
fe/src/components/organisms/NoData/index.tsx
fe/src/components/organisms/NoData/style.ts
fe/src/pages/CalenderPage/index.tsx
fe/src/pages/MainPage/index.tsx
fe/src/utils/date.ts

기존 : 데이터가 없으면 그 해당 달의 달력을 표시하지 않음
개선 : 선택된 기간동안 데이터가 없으면 빈 달력을 표시
데이터가 하나도 없을 때 표시할 NoData 컴포넌트 생성. 추후에 디자인 필요
closes #126 

달력 페이지에서 한 달력이 데이터가 없을 때 빈 달력 출력하도록 수정 및 빈 페이지 추가

---

fe/src/components/atoms/DatePicker/style.ts
fe/src/components/molecules/DateRange/index.tsx
fe/src/components/molecules/DateRange/style.ts
fe/src/components/molecules/DropdownBody/style.ts
fe/src/components/molecules/DropdownHeader/index.tsx
fe/src/components/organisms/MainFilterForm/style.ts
fe/src/components/templates/MainTemplate/style.ts

모달을 적용하여 필터 화면이 중앙에 배치 되도록 하는게 UX가 좋을 것 같아 변경 하였습니다. 
그리고 내부 리스트도 최대 길이를 지정하고 스크롤이 생성되게 하였습니다.

필터 모달로 변경 

---

be/src/controllers/category/index.ts
be/src/libs/error.ts
be/src/middlewares/index.ts
be/src/models/account/index.ts
be/src/models/account/static.ts
be/src/routers/api/category/index.ts
be/src/routers/api/method/index.ts
be/src/services/category/index.ts
fe/src/components/molecules/CategoryDropdown/style.ts
fe/src/pages/CategoryPage/index.tsx

길이가 길어질 경우 레이아웃에 영향이 있을 것으로 추정이 되어 길이를 20자로 제한하는 미들웨어를 추가 하였습니다. 
그리고 서버에 요청 전 FE에서 중복 검사하는 로직을 추가하여 API 요청을 줄였습니다. 

태그 페이지 title 길이 제한 미들웨어 작성 & FE에서 중복 검사 로직 생성

---

be/src/controllers/category/index.ts
be/src/libs/error.ts
be/src/middlewares/index.ts
be/src/models/account/index.ts
be/src/models/account/static.ts
be/src/routers/api/category/index.ts
be/src/routers/api/method/index.ts
be/src/services/category/index.ts
fe/src/components/atoms/DatePicker/index.tsx
fe/src/components/atoms/DatePicker/style.ts
fe/src/components/molecules/CategoryDropdown/style.ts
fe/src/components/molecules/DateRange/index.tsx
fe/src/components/molecules/DateRange/style.ts
fe/src/components/molecules/DropdownBody/style.ts
fe/src/components/molecules/DropdownHeader/index.tsx
fe/src/components/organisms/MainFilterForm/style.ts
fe/src/components/organisms/TransactionInputField/index.tsx
fe/src/components/organisms/TransactionInputField/style.ts
fe/src/components/templates/FormTransaction/style.ts
fe/src/components/templates/MainTemplate/style.ts
fe/src/pages/CategoryPage/index.tsx

<p>
</p>
select 에 css 를 주었습니다. 내부 항목이 길어지면 같이 길어지는 경향이 있어 길이도 지정 하였습니다. 
date picker 같은 경우 필터에서 사용된 컴포넌트를 그대로 사용 하였습니다. 

거래내역 생성 페이지 스타일 수정

---

fe/src/apis/user.ts
fe/src/pages/AccountListPage/index.tsx
fe/src/pages/AuthCheck/index.tsx

브라우저를 재시작 시 가계부 리스트 페이지가 렌더링 되지 않던 것 수정했습니다.
sessionstorage에 있던 useObjId가 없을 때 <></>를 렌더링 하게 임시로 구현했었던 것을, 
없으면 user정보를 받아오는 api를 다시 불러오도록 수정했습니다.
가계부 리스트가 불러오는 중에는 로딩중이라는 글씨가 나오게 했습니다.
closes #236 

브라우저 재시작 시 가계부 리스트 페이지 렌더링 되지 않는 버그 수정

---

fe/src/apis/user.ts
fe/src/components/molecules/DateRange/style.ts
fe/src/components/organisms/MonthInfoHeader/index.tsx
fe/src/components/organisms/MonthInfoHeader/style.ts
fe/src/pages/404Page/index.tsx
fe/src/pages/AccountListPage/index.tsx
fe/src/pages/AuthCheck/index.tsx
fe/src/pages/NotFoundPage/index.tsx
fe/src/pages/NotFoundPage/style.ts

텍스트 중앙정렬하고 채팅버튼 크기와 hover 관련 옵션 추가했습니다.
404페이지를 수정했습니다.
closes #239

MonthHeader 컴포넌트 CSS 수정, 404페이지 수정

---

be/src/controllers/account/index.ts
be/src/services/account/index.ts

기존에 가계부 생성하면 바로 accounts에 users에 들어가도록 구현된 것을 
초대된 사용자 아이디의 invitations 에 생성된 accountObjId를 넣었습니다.
closes #240 

가계부 생성시 바로 등록되는 버그 수정

---

be/src/controllers/account/index.ts
be/src/services/account/index.ts

기존에는 수정했을 때 바로 초대 목록을 users에 덮어썼다. 
- 그래서 기존에 등록된 사용자가 제거 되는 현상 발생
-  바로 등록이 아닌 초대 리스트로 넣어함. 
위에 두 문제를 해결하였습니다.
closes #243

가계부 수정 시 사용자 목록 초가 되는 버그 수정

---

be/src/controllers/account/index.ts
be/src/services/account/index.ts
fe/src/components/atoms/Input/index.tsx
fe/src/components/atoms/PriceTag/index.tsx
fe/src/components/molecules/DateMoneyHeader/index.stories.tsx
fe/src/components/molecules/DateMoneyHeader/index.tsx
fe/src/components/molecules/DateMoneyHeader/style.ts
fe/src/components/molecules/PriceWithSign/index.tsx
fe/src/components/molecules/PriceWithSign/style.ts
fe/src/components/molecules/Transaction/index.tsx
fe/src/components/molecules/Transaction/style.ts
fe/src/components/organisms/TransactionList/index.tsx
fe/src/stores/Category/index.ts
fe/src/stores/Transaction/index.ts
fe/src/stores/Transaction/transactionStoreUtils.ts

기존 메인 페이지에서 항목이 지출인지 수입인지 구별이 잘 안되어서 가격에 색상을 차별하였습니다. 
그리고 미분류 태그는 합계에 안들어 가도록 수정하였습니다. 

메인페이지 미분류 합계에서 제외 및  수입 지출 분리하고 색상구별

---

fe/src/stores/Transaction/index.ts

기존에는 총 금액 별로 정렬이 되어있지 않은 문제가 있었습니다.
총 금액인 totalPrice기준으로 내림차순 정렬한 순으로 보여주도록 수정하였습니다.
closes #255 

[FE] Fix: 파이차트 계산할 때, 가격 순으로 내림차순 정렬할 수 있도록 수정

---

fe/src/components/organisms/TransactionInputField/index.tsx
fe/src/hooks/useTransactionInput.ts
fe/src/pages/CreateTransactionPage/index.tsx
fe/src/pages/UpdateTransactionPage/index.tsx

결제내역 수정 시 원래 있던 카테고리와 결제수단을 디폴트로 두기 위해,
카테고리와 결제수단 리스트 중에서 원래 설정된 값과 일치하는 것은 
option Tag에 selected를 추가하였습니다.
추가로, useTransactionInput hook에서 초기값 설정 하는 부분에서
거래내역이 ''로 설정되었다가 'somethingId'로 설정되면, 렌더링 시 초기값이 ''로 되므로,
수정이라면 ''로 설정하는 것 없이 바로 'somethingId'로 설정하였습니다.
closes #259 

거래내역 수정시 원래 카테고리, 결제내역을 디폴트로 설정

---

fe/src/components/molecules/LineChart/index.tsx
fe/src/components/molecules/PieChart/index.stories.tsx
fe/src/components/organisms/TransactionForm/index.stories.tsx
fe/src/components/organisms/TransactionInputField/index.stories.tsx
fe/src/components/organisms/TransactionInputField/index.tsx
fe/src/hooks/useTransactionInput.ts
fe/src/pages/CreateTransactionPage/index.tsx
fe/src/pages/UpdateTransactionPage/index.tsx
fe/src/utils/__tests__/money.test.ts
fe/src/utils/index.ts

y좌표의의 돈 단위를 요약해서 보여주기 위해
1000원은 1.0천원으로 만들어주는 유틸함수를 구현하여, y좌표를 요약하여 표현해보았습니다.
- 현재 이 함수는 천억까지 커버를 할 수 있도록 하였습니다.
단위를 더 만드는 것은 어려운 일이 아니지만, 
어느 정도의  돈의 단위를 넘어가는 수준에서는 거래내역에서 입력을 하지 못하도록 
막는것은 어떨까요?
closes #121

라인차트에서 y좌표의 단위 변경

---

be/src/libs/error.ts
be/src/middlewares/index.ts
be/src/routers/api/transaction/index.ts
fe/src/components/molecules/LineChart/index.tsx
fe/src/components/molecules/PieChart/index.stories.tsx
fe/src/components/organisms/TransactionForm/index.stories.tsx
fe/src/components/organisms/TransactionInputField/index.stories.tsx
fe/src/components/organisms/TransactionInputField/index.tsx
fe/src/hooks/useTransactionInput.ts
fe/src/pages/CreateTransactionPage/index.tsx
fe/src/pages/UpdateTransactionPage/index.tsx
fe/src/utils/__tests__/money.test.ts
fe/src/utils/index.ts
fe/src/utils/validator.ts

- 결제내역 입력 시 음수가 들어가지 않도록 프론트, 백엔드에서 처리해주었습니다.
- 결제내역에서  거래처 입력시 스페이스를 계속 누른 후, 입력하면 저장이 되는 것을 수정하였습니다.
- 초기 거래내역 추가시 금액을 placeholder로 두었습니다.
closes #270
closes #271
closes #272

거래내역 금액에 음수 안들어가도록, 거래처 입력시 스페이스바만 있는 것은 안되도록, 초기 금액에 placeholder

---

fe/package.json
fe/src/components/atoms/DatePicker/index.tsx
fe/src/components/atoms/PriceTag/index.tsx
fe/src/components/organisms/MonthInfoHeader/index.tsx
fe/src/components/organisms/TransactionList/index.tsx
fe/src/stores/Transaction/index.ts
fe/src/utils/date.ts

초반에 `startDate, endDate` 지정하는 부분에서 IOS에서 지원하지않는 타입으로 에러가 출력되었습니다. 
dayjs 를 사용하여 UTC로 통일하여 초기값 셋팅을 하였습니다.
closes #274 
closes #238 

IOS 에서 안들어가지는 버그 수정 및 price 수정

---

fe/package.json
fe/src/components/atoms/DatePicker/index.tsx
fe/src/components/atoms/PriceTag/index.tsx
fe/src/components/organisms/MonthInfoHeader/index.tsx
fe/src/components/organisms/TransactionList/index.tsx
fe/src/components/templates/CategoryTemplate/index.tsx
fe/src/components/templates/CategoryTemplate/style.ts
fe/src/components/templates/FormTransaction/index.tsx
fe/src/components/templates/FormTransaction/style.ts
fe/src/components/templates/MainTemplate/index.tsx
fe/src/components/templates/MainTemplate/style.ts
fe/src/pages/CategoryPage/index.tsx
fe/src/stores/Transaction/index.ts
fe/src/styles/GlobalStyle.ts
fe/src/utils/date.ts

순서대로 스마트폰, 태블릿 , 데스크탑입니다. 
-   [x] 페이지별 breakPoint를 잡아서 값 조정
-  [x]  폰트 사이즈 조정
closes #276 

기기에 맞는 width, font-size 수정

---

be/src/controllers/category/index.ts
be/src/services/category/index.ts
fe/src/pages/CategoryPage/index.tsx

if에서 `&`연산으로 검사하는 부분을 따로 함수로 추출하였습니다. 
로컬에서 테스트 할 때는 정상적으로 동작하는 것을 확인하였습니다.
FE와 마찬가지로 검사하는 로직을 따로 함수로 추출하였습니다.

카테고리 중복 검사 로직 수정

---

fe/public/index.html
fe/src/components/atoms/DatePicker/style.ts
fe/src/components/atoms/Input/style.ts
fe/src/components/organisms/TransactionInputField/style.ts
fe/src/styles/GlobalStyle.ts

Input에 들어가는 텍스트 크기가 16px미만이면 IOS에서 자동으로 zoom-in을 해서 Input에 들어가는 텍스트 크기는 16px로 고정했습니다.
datePicker가 모바일에서 사용하기 어려웠었는데 CSS로 빈 공백 최대한 줄여서  사용하기 편하게 했습니다.
-   [x] Input관련 클릭했을 때 확대 안되게 잘 되는지
closes #285 
closes #289 

모바일에서 Input 클릭 시 zoom-in되는 것 / Datepicker 모바일에서 사용하기 어려웠던 것 수정

---

fe/src/hooks/useAccountInfo.ts
fe/src/pages/AccountListPage/index.tsx

세션 스토리지에 가계부의 `id, title, owner`를 저장하여 새로고침 했을 때 새로 요청을 안보내도록 하기 위한 작업을 하였습니다. 

세션 스토리지에 가계부 정보 저장

---

be/src/libs/error.ts
be/src/middlewares/index.ts
fe/src/components/atoms/Input/index.tsx
fe/src/components/atoms/Message/index.stories.tsx
fe/src/components/atoms/Message/index.tsx
fe/src/components/atoms/Message/style.ts
fe/src/components/organisms/TransactionInputField/index.stories.tsx
fe/src/components/organisms/TransactionInputField/index.tsx
fe/src/components/organisms/TransactionInputField/style.ts
fe/src/pages/CreateTransactionPage/index.tsx
fe/src/pages/UpdateTransactionPage/index.tsx
fe/src/styles/theme.ts
fe/src/utils/validator.ts

- 거래내역의 에러가 생기면, 해당 폼에서 에러를 알려줄 수 있도록 하였습니다.
- 에러 메시지는 Message 컴포넌트를 만들어서 띄워주었습니다.
closes #293 
closes #291

거래내역 폼에서 최대값이 1조 미만 & 거래내역 폼 에러 메시지 수정

---

be/src/middlewares/index.ts
be/src/services/account/index.ts
fe/src/pages/AccountUpdatePage/index.tsx

반환 값을 받는 부분이 axios로 인해서 res.data를 미리 리턴했기 때문에 res.error 로 접근 해야 반한된 에러 메세지 접근 할 수 있도록 수정 하였습니다.
타이틀검사 미들웨어에서 수정 하고자하는 메소드일때 자기자신이면 통과하도록 미들웨어 수정

가계부 생성/수정 페이지 중복 검사 로직 수정 

---

be/src/middlewares/index.ts
fe/src/components/molecules/Transaction/index.tsx
fe/src/components/molecules/Transaction/style.ts

- 모바일 환경
- 데스크탑 환경
closes #309

거래처에서 이름 길어졌을 때, ...으로 처리

---

fe/src/styles/GlobalStyle.ts

IOS에선 기본 스타일을 강제하는데 그것 푸는 CSS코드를 추가했습니다.
-   [x] 모양 데스크탑 버전이랑 비슷하게 보이는지
closes #290 

IOS에서 버튼 모양 다른 것 수정

---

be/src/middlewares/index.ts
fe/src/apis/account.ts
fe/src/pages/AccountUpdatePage/index.tsx

이번에는 진짜 될 것입니다. 
생성은 현재 사용자 이름, 타이틀 로 검색하여 null 이 아니면 에러를 던지게 했습니다. 
수정은 가계부 주인이름, 아이틀, 가계부 id 로 검색하여 null이 아니면 에러를 던지게 했습니다. 

[FE] Fix : 수정 미들웨어 수정

---

fe/src/components/molecules/CategoryDropdown/style.ts

메인 화면 처럼 마우스 올리면 색이 나오도록 하였습니다. 

[FE] Style : 카테고리 호버 색 추가

---

fe/src/hooks/useTransactionInput.ts

미분류로 된 거래내역에서 첫 번째 카테고리를 두고 수정을 할 경우 지정이 안되는 버그가 있었습니다.
미분류는 카테고리 리스트에 없으므로, select을 할 수가 없어서
카테고리가 미분류인 경우는, 미분류가 아닌 카테고리 중 하나를 선택하도록 수정하였다.
closes #331 

[FE] Fix: 미분류에서 수정 시 첫 번째 카테고리를 디폴트로 수정

---

fe/src/components/molecules/Checkbox/style.ts
fe/src/components/molecules/LineChart/index.tsx
fe/src/components/molecules/LineChart/style.ts
fe/src/components/organisms/PieChartDetail/index.tsx
fe/src/components/organisms/PieChartDetail/style.ts
fe/src/components/organisms/PieChartOverview/style.ts
fe/src/utils/__tests__/math.test.ts
fe/src/utils/math.ts

- 마우스 올렸을 때 버튼의 색 변경
- 수입. 지출에 따라 다른 색 보여지도록 수정
- 라인 차트 애니메이션에서 라인의 길이를 계산한 후, stroke-dasharray에 넣는 것으로 수정한다.
closes #339 

통계페이지의 버튼 css 수정 & 타입에 따라 컬러 변경 & 애니메이션 길이 계산 추가

---

fe/src/components/molecules/CalendarOneDate/index.tsx
fe/src/components/molecules/CalendarOneDate/style.ts
fe/src/components/organisms/AccountImageTitleUpdate/style.ts
fe/src/components/organisms/Calendar/style.ts
fe/src/components/organisms/CalendarBind/index.tsx
fe/src/styles/GlobalStyle.ts

데스크탑 사이즈에서 에러메세지 치우쳤던 것 수정했습니다.
-[x] 데스크탑에서 중복된 이름입니다가 너무 오른쪽에 치우침 수정
closes #322

가계부 리스트 에러메세지 오른쪽에 치우쳤던 것 수정

---

fe/src/components/molecules/CalendarOneDate/index.tsx
fe/src/components/molecules/CalendarOneDate/style.ts
fe/src/components/organisms/Calendar/style.ts
fe/src/components/organisms/CalendarBind/index.tsx
fe/src/styles/GlobalStyle.ts

* 1월 1일까지 하면 데이터 없어도 1월 달력이 보입니다.
* 날짜 하나에서 보이는 글자 크기 수정하고 요약된 돈 보여주도록 수정했습니다.
closes #319
closes #301
closes #287

기간 해당하는 달력 모두 보여주기 / 달력 한칸 보이는 돈 요약해서 보여주도록 수정

---

fe/src/components/molecules/LineChart/index.tsx
fe/src/components/organisms/LineChartOverview/index.tsx

데이터 없을 때 라인차트 그래프 구현

---

fe/src/components/organisms/MonthInfoHeader/index.tsx
fe/src/components/organisms/MonthInfoHeader/style.ts

width가 300px정도일 때, 금액이 크면 배치가 이상해져서, 작은 화면인 iphone 5/SE 기준으로
month header bar의 배치를 조절하였습니다.
**iphone 5/SE**
- 채팅 크기 줄임
- 수입, 지출을 column으로 배치
- 시작일, 마지막일 부분의 패딩 없앰

month header바 반응형 구현

---

fe/src/components/molecules/CalendarOneDate/index.tsx
fe/src/components/molecules/CalendarOneDate/style.ts
fe/src/components/organisms/DateTransactionModal/style.ts
fe/src/components/organisms/HeaderBar/index.tsx
fe/src/components/organisms/HeaderBar/style.ts
fe/src/components/organisms/NoData/style.ts
fe/src/components/templates/MainTemplate/style.ts
fe/src/pages/AccountListPage/index.tsx
fe/src/pages/CalendarPage/index.tsx
fe/src/pages/CalendarPage/styles.ts
fe/src/pages/CategoryPage/index.tsx
fe/src/pages/ChattingPage/index.tsx
fe/src/pages/MainPage/index.tsx
fe/src/pages/StatisticsDetailPage/index.tsx
fe/src/pages/StatisticsPage/index.tsx

다른 가계부로 이동할 때 이전 가계부 목록이 잠깐 보였던 버그가 있었는데 이제 보이지 않고 로딩화면이 뜹니다.
-   [ ] 메인페이지에서 transaction받아오고 있는 중에 로딩페이지를 보여주는지
closes #348

달력 페이지 모달 깨지는 것 수정 / 달력페이지 CSS 수정 / 헤더바 CSS 추가 / 메인페이지 로딩화면 추가

---

fe/src/pages/MainPage/TransactionDateList.tsx
fe/src/utils/date.ts

IOS에선 new Date('2020-6-7') 하면 invaild라고 나오고 06-07로 해줘야 했던 것 반영

IOS에서 TransactionHeader에 Undefined가 나오던 것 수정

---

fe/src/components/organisms/Calendar/index.tsx

* 시작 요일 (일요일 or 월요일) 이 되면 한 Row를 새로 생성하도록 달력을 만들었는데 이 것 때문에 하루가 당겨저 출력됨
* 시작요일이 일요일이면 토요일일 때 새 Row를 만들고 월요일이면 일요일일 때 새 Row를 만들도록 수정

[FE] Fix: 달력 하루씩 밀려있던 버그 수정
